http://localhost:3000/upload
###
POST http://localhost:3000/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=MyBoundary

--MyBoundary
Content-Disposition: form-data; name="file"; filename="sample_data.csv"
Content-Type: text/csv

< /Users/k22002/AndroidStudioProjects/test1/2_sample_data.csv
--MyBoundary--
### Send raw CSV data
POST http://192.168.1.139:3000/upload HTTP/1.1
Content-Type: text/csv

id,Heart_Rate,Timestamp
1,1000,2024-12-17 07:55:29
###

< /path/to/your/2_sample_data.csv
--MyBoundary--

http://localhost:3000/reset-table